### PR TITLE
Implemented Fake build as F# project

### PR DESCRIPTION
**Pull request by xperiandri**

### CODE REVIEW

**Comment by xperiandri** [comment]
@valbers try this. It will fix a build for the other branches

**Comment by valbers** [comment]
haha, it's crazy, man, but it works! 😄 👍

**Review by valbers — APPROVED** [review]
LGTM

**Comment by xperiandri** [comment]
@ivelten @mickhansen @GBirkel if no comments or objections I'll merge tomorrow

**Review by mickhansen — APPROVED** [review]

**Pull request merged**
