### PR TITLE
Added Fantomas settings

### PR DESCRIPTION
**Pull request by xperiandri**
@jberzy if you agree with the proposed .egitorconfig settings I will style all the project using them

### CODE REVIEW

**Comment by xperiandri** [comment]
@ivelten, @mickhansen, @nikhedonia

1. What do you think about the proposed settings?
2. Do you prefer the first or the second commit settings?
3. Would you like anything to add? Maybe about JavaScript

**Comment by xperiandri** [comment]
@aggieben

**Comment by aggieben** [comment]
@xperiandri are you referring to #284 as the proposed changes, or did you mean to include a changed .editorconfig in this PR?

**Comment by xperiandri** [comment]
#284 is closed. We work with this PR only. So the questions are about changes in this PR.

**Comment by xperiandri** [comment]
@aggieben I did a mistake

**Comment by xperiandri** [comment]
This PR uses incorrect branch as source

**Comment by xperiandri** [comment]
I close it and reopen #284

**Pull request closed without merging**
