### PR TITLE
Complete the AST according to the June 2018 GraphQL spec edition

### PR DESCRIPTION
**Pull request by haf**
- Add some code-docs so that developers using the AST can read about
  what they are doing
- Add TypeSystemDefinition and TypeSystemExtension to the Definition DU
- Move DirectiveLocation from TypeSystem to Ast
- Update usages

### CODE REVIEW

**Comment by haf** [comment]
Is this wanted?

**Comment by johnberzy-bazinga** [comment]
Hi @haf 

I sent you a message on gitter a few days ago. We're definitely wanting this PR, but since this is a breaking change we're waiting until we complete the other 2.0 changes in.
Thanks,
John

**Comment by xperiandri** [comment]
@haf is it relevant?
If so, could you rebase this and make mergable?

**Comment by haf** [comment]
Relevant: Yes, IMO without seeing what work of mine that authors of this repo duplicated.

Can rebase: no, sorry, not without payment. The code is as-is and I'm fine with it being rejected or merged, whichever suits you best.

**Comment by xperiandri** [comment]
@haf, pinged you in F# Slack

**Pull request closed without merging**
