### PR TITLE
bugfix/issue-365-enum-encoding

### PR DESCRIPTION
**Pull request by njlr**
* Enums now encoded using name
 * Adds test

### CODE REVIEW

**Comment by xperiandri** [comment]
Look great. Is it ready for merge?

**Comment by xperiandri** [comment]
@nikhedonia, @mickhansen any comments or suggestions?

**Comment by njlr** [comment]
> Look great. Is it ready for merge?

I think so!

Main thing to check is if the new behavior is exactly what we want as this will be a breaking change in _some_ cases. 

1. Behavior is the same:

```fsharp
type private Fruit =
  | Apple
  | Banana
  | Cherry

let private enumType =
  Define.Enum(
    "Fruit",
    [
      Define.EnumValue("Apple", Apple)
      Define.EnumValue("Banana", Banana)
      Define.EnumValue("Cherry", Cherry)
    ]
  )
```

2. Behavior is the same:

```fsharp
type private Fruit =
  | Apple
  | Banana
  | Cherry
  with
    override this.ToString() = 
      match this with
      | Apple -> "APPLE"
      | Banana -> "BANANA"
      | Cherry -> "CHERRY"

let private enumType =
  Define.Enum(
    "Fruit",
    [
      Define.EnumValue("APPLE", Apple)
      Define.EnumValue("BANANA", Banana)
      Define.EnumValue("CHERRY", Cherry)
    ]
  )
```

3. Behavior is different:

```fsharp
type private Fruit =
  | Apple
  | Banana
  | Cherry

let private enumType =
  Define.Enum(
    "Fruit",
    [
      Define.EnumValue("APPLE", Apple)
      Define.EnumValue("BANANA", Banana)
      Define.EnumValue("CHERRY", Cherry)
    ]
  )
```

**Comment by xperiandri** [comment]
While working with GraphQL and this library in particular I found that I must validate a scheme with the original JavaScript library via Node.js and perform integration tests from a generated client down to a database gathering all the available fields.
Only that ensures that everything works as expected.

**Comment by mickhansen** [comment]
Great! `Define.EnumValue("APPLE", Apple)` definitely threw me for a loop when I first started implementing.

Only question is how we handle breaking changes, where are we in terms of publishing a new nuget package? This might require a major version bump.

Not even sure if we need to consider this a breaking change, more of a bug fix since the `Define.EnumValue("APPLE", Apple)` case never worked properly IIRC.

**Comment by nikhedonia** [comment]
I like this and happy to merge

**Pull request merged**
