### PR TITLE
Input object validation

### PR DESCRIPTION
**Pull request by xperiandri**
* Implemented Fake as project instead of F# script to support .NET 7
* Added .NET 7 target for server projects

### CODE REVIEW

**Comment by xperiandri** [comment]
@valbers have a look if you have time

**Comment by xperiandri** [comment]
@njlr could you review too?

**Comment by xperiandri** [comment]
@valbers @njlr @ivelten @mickhansen ready for review too

**Comment by mickhansen** [comment]
@xperiandri Large changeset so trying to wrap my head around it. Could you add some text to describe what it achieves?
Looks like this allows developers to add a validation fn to InputObjects - It does not attempt to add schema validation of say variables via JSON, correct?

**Comment by xperiandri** [comment]
Correct.
Here is a file that showcases the scenarios
https://github.com/fsprojects/FSharp.Data.GraphQL/blob/input-object-validation/tests/FSharp.Data.GraphQL.Tests/Variables%20and%20Inputs/InputObjectValidatorTests.fs

**Comment by mickhansen** [comment]
> Correct. Here is a file that showcases the scenarios https://github.com/fsprojects/FSharp.Data.GraphQL/blob/input-object-validation/tests/FSharp.Data.GraphQL.Tests/Variables%20and%20Inputs/InputObjectValidatorTests.fs

@xperiandri Thank you, will take a look. Might also be worthwhile to include some documentation of the feature in this PR?

**Comment by xperiandri** [comment]
Good idea, just need to figure out what and where to modify 🙂

**Review by valbers — APPROVED** [review]
Nice. LGMT.

**Pull request merged**
