### PR TITLE
Making Shared project have its own package

### PR DESCRIPTION
**Pull request by ivelten**
With this PR, I am separating `FSharp.Data.GraphQL.Shared` to have it's own Nuget package, and setting 
`FSharp.Data.GraphQL.Server`, `FSharp.Data.GraphQL.Client` and `FSharp.Data.GraphQL.Server.Middlewares` to depend on it.

### CODE REVIEW

**Comment by xperiandri** [comment]
Does your idea include this too?

**Comment by ivelten** [comment]
> Does your idea include this too?

Yes, my idea was to separate Shared into its own package, then after that, splitting Shared into smaller packages. There are still conflicts that must be resolved, right? I will take a look tonight and try to solve them.

**Comment by xperiandri** [comment]
Yes, try that, please

**Comment by xperiandri** [comment]
Maybe it will be easier to do an interactive rebase removing unnecessary changes or going one by one

**Comment by xperiandri** [comment]
Done in #403

**Pull request closed without merging**
