### PR TITLE
Add subscription and defer support

### PR DESCRIPTION
**Pull request by TOTBWF**
This PR builds off of #117 to add streaming subscriptions. To create a subscription, you have to do 2 things:

1. Add the subscription to the schema:
```f#let Subscription = 
    Define.SubscriptionObject<Root>(
        name = "Subscription",
        fields = [
            Define.SubscriptionField(
                "name",
                RootType,
                InputType,
                "description",
                [ Define.Input("id", String) ],
                (fun ctx r p -> \*Filter logic here*\ ...))])
```
2. Pass an implementation of `ISubscriptionProvider` to the SchemaConfig 
    ISubscriptionProvider (No need for unsubscribe, that should be handled by disposing of the IObservable):
```f#
type ISubscriptionProvider =
    interface
        /// Registers a new subscription type
        /// Called at schema compilation time
        abstract member Register: Subscription -> unit
        /// Creates an active subscription, and returns the IObservable stream of POCO objects that will be projected on
        abstract member Add : ResolveFieldContext -> obj -> string -> IObservable<obj>
        /// Publishes an event to the subscription system given the identifier of the subscription type
        abstract member Publish<'T> : string -> 'T -> unit
```
A default implementation is provided.

### CODE REVIEW

**Comment by TOTBWF** [comment]
Just an update, I fixed a few issues with Spec compliance and null/error propagation and added paths to error messages, as per the spec

**Comment by Horusiath** [comment]
@TOTBWF What is the status on this one?

**Comment by TOTBWF** [comment]
I'm just fixing some edge cases with lists of unions/interfaces and adding some tests, it should be ready within the next few days

**Comment by TOTBWF** [comment]
This should be good to go!

**Comment by Horusiath** [comment]
@johnberzy-bazinga we need to fix CI. It seems to be broken.

**Comment by johnberzy-bazinga** [comment]
Yeah, we're still waiting on travis-ci/travis-build#1060. I'm not sure if there is a work around. I'll take a look at it a bit later.

**Comment by TOTBWF** [comment]
Just for reference, I did some benchmarking with the fixed benchmark code comparing the old and new execution models on both Mono and .NetCore, Here are the results: 
benchmarks
Keep in mind that these are zero-latency fetches.

**Comment by Horusiath** [comment]
Are we ready to merge?

**Comment by TOTBWF** [comment]
Yeah, we are good to go

**Pull request merged**
